---
title: "Math 162"
subtitle: "Class 17"
format: 
    revealjs:
        chalkboard:
            theme: whiteboard
            src: 162_class17_wi24.json
        html-math-method: mathjax
        include-in-header:
          - text: |
              <script>
              MathJax = {
                options: {
                  menuOptions: {
                    settings: {
                      assistiveMml: false
                    }
                  }
                }
              };
              </script>
---

Calculate $\displaystyle \int_{-2}^1 \frac{1}{x^2}\;dx$

---

Calculate $\displaystyle \int_{-2}^1 \frac{1}{x^{1/3}}\;dx$

## P-integrals {.smaller}

$$\int_0^1 \frac{1}{x^p}\;dx$$

## P-integrals {.smaller}

$$\int_1^\infty \frac{1}{x^p}\;dx$$

## Comparison Theorem

Does $\displaystyle \int_1^\infty \frac{1}{xe^x}\;dx$ converge?

## Comparison Theorem

Does $\displaystyle \int_e^\infty \frac{\ln x}{x}\;dx$ converge?

## Infinite Sequences

Sequence:

::: {.incremental}
-   A (possibly infinite) list of numbers
-   A _function_ from (a subset of) integers to real numbers
:::

## Notation and Terminology

## Examples

::: {.incremental}
-   $a_n = 1 + 2^n$, $n = 0, 1, 2, \ldots$
-   $\left\{\frac{1}{n+1}\right\}_{n=1, 2, \ldots}$
-   $\left\{\frac{1}{n}\right\}_{n=2, 3, \ldots}$
-   $c_0 = 2$ and $c_n = 2c_{n-1} + 3$ for $n > 0$
:::

## Arithmetic Sequences

$a_n = a_{n-1} + d$ for $n > 0$

## Geometric Sequences

$g_n = r\cdot g_{n-1}$ for $n > 0$

## Factorials

*   $a_0 = 1$
*   $a_n = n\cdot a_{n-1}$ for $n > 0$

. . .

*   $d_0 = 1$
*   $d_1 = 1$
*   $d_n = n\cdot a_{n-2}$ for $n > 1$

## Increasing and Decreasing Sequences

::: {.incremental}
-   A sequence $a_n$ is _increasing_ if $a_{n+1} \ge a_n$ for all $n$.
-   A sequence $a_n$ is _strictly increasing_ if $a_{n+1} > a_n$ for all $n$.
-   A sequence $a_n$ is _decreasing_ if $a_{n+1} \le a_n$ for all $n$.
-   A sequence $a_n$ is _strictly decreasing_ if $a_{n+1} < a_n$ for all $n$.
-   A sequence $a_n$ is _eventually increasing_, or _increasing for all $n \ge n_0$, if $a_{n+1} \ge a_n$ for all $n \ge n_0$.
-   A sequence $a_n$ is _eventually decreasing_, or _decreasing for all $n \ge n_0$, if $a_{n+1} \le a_n$ for all $n \ge n_0$.
:::

## Monotone Sequences

::: {.incremental}
-   A sequence is called _monotone_ if it is either _increasing_ or _decreasing_.
-   A sequence is called _strictly monotone_ if it is either _strictly increasing_ or _strictly decreasing_.
-   A sequence is called _eventually monotone_ if it is either _eventually increasing_ or _eventually decreasing_.
:::

## Examples

## Bounded sequences

::: {.incremental}
-   A sequence $a_n$ is _bounded from above_ by $B$ if $a_n \le B$ for each $n$.
-   A sequence $a_n$ is _bounded from below_ by $b$ if $a_n \ge b$ for each $n$.
-   A sequence is __bounded__ if it is _bounded from below_ and _bounded from above_.
:::

## Examples

## Limits of Sequences

__Definition:__ We way that an infinite sequence $a_n$ has a _limit_ $L$, or
_converges to_ $L$, if for every $\varepsilon > 0$ there exists an integer $N$
such that $\left\lvert a_n - L\right\rvert < \varepsilon$ for each $n \ge N$.

Notation: $\displaystyle \lim_{n\to\infty} a_n = L$

. . .

If a sequence has a limit, we say that it is _convergent_.

. . .

Otherwise, we say that it is _divergent_.

